# Generated by Django 3.1.3 on 2021-12-02 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(default='', max_length=150, null=True, verbose_name='indiquez votre adresse de depart')),
                ('arrive', models.CharField(default='', max_length=150, null=True)),
                ('adresse', models.CharField(max_length=150)),
                ('passagers', models.PositiveIntegerField(verbose_name='indiquez le nombre de personnes ')),
                ('baggages', models.PositiveIntegerField(null=True, verbose_name=' bagagges etc ..')),
                ('num_phone', phonenumber_field.modelfields.PhoneNumberField(default='+972', max_length=128, null=True, region=None)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
