# Generated by Django 3.1.3 on 2021-12-29 18:28

from django.conf import settings
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carpool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('car', models.CharField(default='Regular car', max_length=255)),
                ('car_image', models.ImageField(default='hotelsample.jpg', null=True, upload_to='images/')),
                ('num_phone', phonenumber_field.modelfields.PhoneNumberField(default='+972', max_length=128, null=True, region=None, unique=True)),
                ('client', models.ManyToManyField(related_name='user_client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
