# Generated by Django 3.1.3 on 2022-01-06 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0003_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 16, 4, 50, 583258)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 16, 4, 50, 583258)),
        ),
    ]
