# Generated by Django 4.0 on 2022-08-14 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0007_auto_20220111_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='body',
            field=models.CharField(max_length=255, null=True, verbose_name='Avez vous des remarques a faire ?'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='date_depart',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 14, 39, 43, 156853)),
        ),
        migrations.AlterField(
            model_name='offre',
            name='exp_date',
            field=models.DateTimeField(default=2300),
        ),
        migrations.AlterField(
            model_name='post',
            name='arrive',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='indiquez votre adresse d arrivé'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 14, 39, 43, 156853)),
        ),
        migrations.AlterField(
            model_name='post',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 14, 14, 39, 43, 156853)),
        ),
    ]
