# Generated by Django 4.0 on 2022-10-18 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('carpool', '0010_alter_offre_date_depart_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='ville',
            field=models.CharField(default='Tel Aviv', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='ville',
            field=models.CharField(default='Tel Aviv', max_length=150),
        ),
        migrations.AlterField(
            model_name='offre',
            name='date_depart',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 14, 54, 22, 351767)),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 14, 54, 22, 351767)),
        ),
        migrations.AlterField(
            model_name='post',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 14, 54, 22, 351767)),
        ),
    ]
