# Generated by Django 4.0 on 2022-10-20 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0012_alter_offre_date_depart_alter_offre_depart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='exp_date',
        ),
        migrations.AlterField(
            model_name='offre',
            name='adresse',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='date_depart',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 11, 15, 33, 808610), null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='depart',
            field=models.CharField(default='Milan', max_length=150, null=True, verbose_name='indiquez votre adresse de depart'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='ville',
            field=models.CharField(default='Milan', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 11, 15, 33, 808610)),
        ),
        migrations.AlterField(
            model_name='post',
            name='depart',
            field=models.CharField(default='Milan', max_length=150, null=True, verbose_name='indiquez votre adresse de depart'),
        ),
        migrations.AlterField(
            model_name='post',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 11, 15, 33, 808610)),
        ),
        migrations.AlterField(
            model_name='post',
            name='ville',
            field=models.CharField(default='Milan', max_length=150),
        ),
    ]
