# Generated by Django 4.0 on 2022-10-20 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0013_remove_offre_exp_date_alter_offre_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='body',
            field=models.CharField(max_length=255, null=True, verbose_name='combien de place disponible ?'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='date_depart',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 11, 32, 55, 885471), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 11, 32, 55, 885471)),
        ),
        migrations.AlterField(
            model_name='post',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 11, 32, 55, 885471)),
        ),
    ]
