# Generated by Django 4.0 on 2022-10-20 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0015_alter_offre_arrive_alter_offre_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='body',
        ),
        migrations.AlterField(
            model_name='offre',
            name='arrive',
            field=models.CharField(default='tel-aviv', max_length=150, verbose_name='indiquez votre destination final  '),
        ),
        migrations.AlterField(
            model_name='offre',
            name='date_depart',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 12, 47, 7, 248307), null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='depart',
            field=models.CharField(default='Milan', max_length=150, null=True, verbose_name='indiquez votre ville et adresse de depart ou un lieu'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='passagers',
            field=models.PositiveIntegerField(verbose_name='indiquez le nombre de place disponible '),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 12, 47, 7, 248307)),
        ),
        migrations.AlterField(
            model_name='post',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 12, 47, 7, 248307)),
        ),
    ]
