# Generated by Django 4.0 on 2022-10-24 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0016_remove_offre_body_alter_offre_arrive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='adresse',
        ),
        migrations.AlterField(
            model_name='offre',
            name='date_depart',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 13, 12, 16, 44929), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 13, 12, 16, 44929)),
        ),
        migrations.AlterField(
            model_name='post',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 13, 12, 16, 44929)),
        ),
    ]
